### ISSUE TITLE
dxfeed doesn't seem to have EventType type

### ISSUE THREAD

**Issue by jmatzen** [tastyware/tastytrade-cli#10]
```
$ tt
Traceback (most recent call last):
  File "/Users/john/depot/tastytrade/venv/bin/tt", line 5, in <module>
    from ttcli.app import main
  File "/Users/john/depot/tastytrade/venv/lib/python3.12/site-packages/ttcli/app.py", line 6, in <module>
    from ttcli.option import option
  File "/Users/john/depot/tastytrade/venv/lib/python3.12/site-packages/ttcli/option.py", line 8, in <module>
    from tastytrade.dxfeed import EventType, Greeks, Quote
ImportError: cannot import name 'EventType' from 'tastytrade.dxfeed' (/Users/john/depot/tastytrade/venv/lib/python3.12/site-packages/tastytrade/dxfeed/__init__.py)
```

**Comment by Graeme22** [comment]
Hi, this is because `EventType` was removed in v9.0. If you do `pip install tastytrade==8.5` you can probably get it working, though hopefully I can get the CLI updated soon as it hasn't been touched in a while.

**Comment by Graeme22** [comment]
This should be fixed in the latest release!
