### ISSUE TITLE
Compatibility Issues with latest tastytrade-sdk, tastytrade & websocket versions under python 3.9?

### ISSUE THREAD

**Issue by ctsc-tcn** [tastyware/tastytrade-cli#14]
I am getting conflicting websocket requirements, is this a known issue or individual to my setup?

**Comment by Graeme22** [comment]
Can you post the output of `pip freeze`?

**Comment by ctsc-tcn** [comment]
WARNING: No metadata found in ./ttpython/lib/python3.9/site-packages
annotated-types==0.7.0
anyio==4.7.0
asyncclick==8.1.7.2
bidict==0.22.1
certifi==2024.12.14
charset-normalizer==3.4.1
exceptiongroup==1.2.2
exchange_calendars==4.5.6
h11==0.14.0
httpcore==1.0.7
httpx==0.28.1
idna==3.10
injector==0.20.1
korean-lunar-calendar==0.3.1
markdown-it-py==3.0.0
mdurl==0.1.2
numpy==2.0.2
pandas==2.2.3
pandas_market_calendars==4.4.2
pydantic==2.10.4
pydantic_core==2.27.2
Pygments==2.18.0
pyluach==2.2.0
python-dateutil==2.9.0.post0
pytz==2024.2
requests==2.29.0
rich==13.9.4
six==1.17.0
sniffio==1.3.1
StrEnum==0.4.15
tastytrade==9.5
tastytrade-cli==0.1
tastytrade-sdk==0.0.30
toolz==1.0.0
typing_extensions==4.12.2
tzdata==2024.2
ujson==5.10.0
urllib3==1.26.20
websockets==11.0.3

**Comment by Graeme22** [comment]
Try running this:

```bash
pip uninstall tastytrade-sdk
pip install -U tastytrade-cli
```

**Comment by ctsc-tcn** [comment]
appreciate the suggestion..

$ tt pf
Traceback (most recent call last):
  File "/Users/hhgg/Library/Mobile Documents/com~apple~CloudDocs/C_Code/J_Workbench/cli-tt/clipython/bin/tt", line 7, in <module>
    from ttcli.app import main
  File "/Users/hhgg/Library/Mobile Documents/com~apple~CloudDocs/C_Code/J_Workbench/cli-tt/clipython/lib/python3.9/site-packages/ttcli/app.py", line 6, in <module>
    from ttcli.option import option
  File "/Users/hhgg/Library/Mobile Documents/com~apple~CloudDocs/C_Code/J_Workbench/cli-tt/clipython/lib/python3.9/site-packages/ttcli/option.py", line 9, in <module>
    from tastytrade.dxfeed import EventType, Greeks, Quote
ImportError: cannot import name 'EventType' from 'tastytrade.dxfeed' (/Users/hhgg/Library/Mobile Documents/com~apple~CloudDocs/C_Code/J_Workbench/cli-tt/clipython/lib/python3.9/site-packages/tastytrade/dxfeed/__init__.py)
(clipython) 

 pip freeze
annotated-types==0.7.0
anyio==4.7.0
asyncclick==8.1.7.2
certifi==2024.12.14
exceptiongroup==1.2.2
exchange_calendars==4.5.6
h11==0.14.0
httpcore==1.0.7
httpx==0.28.1
idna==3.10
korean-lunar-calendar==0.3.1
markdown-it-py==3.0.0
mdurl==0.1.2
numpy==2.0.2
pandas==2.2.3
pandas_market_calendars==4.5.1
pydantic==2.10.4
pydantic_core==2.27.2
Pygments==2.18.0
pyluach==2.2.0
python-dateutil==2.9.0.post0
pytz==2024.2
rich==13.9.4
six==1.17.0
sniffio==1.3.1
tastytrade==9.5
tastytrade-cli==0.1
toolz==1.0.0
typing_extensions==4.12.2
tzdata==2024.2
websockets==14.1
(clipython) 


no one else having any of these issues?

**Comment by Graeme22** [comment]
According to the output you're on version 0.1 of the CLI still! Try running `pip install -U tastytrade-cli`

**Comment by ctsc-tcn** [comment]
Running / Installing w Python3.13 did the trick - thank you very much
